version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'bandportal'
      POSTGRES_USER: 'bandportal'
      POSTGRES_PASSWORD: 'bandportal'
    networks: [backend]
  backend:
    image: stehlvo2/bandportal-backend:0.1
    depends_on:
      - postgres
    restart: always
    ports:
      - '8080:8080'
    networks: [backend]
  dashboard:
    image: stehlvo2/bandportal-frontend:0.1
    depends_on:
      - backend
    restart: always
    ports:
      - '3000:3000'
    networks: [backend]

networks:
  backend: null
